[package]
name = "coc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "a_lambda_main"
path = "src/a_lambda_main.rs"
